// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleHelper: typeof import('./components/ArticleHelper.vue')['default']
    IconImage: typeof import('./components/IconImage.vue')['default']
    IllustrationContainer: typeof import('./components/IllustrationContainer.vue')['default']
    Paragraph: typeof import('./components/Paragraph.vue')['default']
    SectionContainer: typeof import('./components/SectionContainer.vue')['default']
  }
}

export { }
